language: php 

php:
  - 5.6

notifications:
  email: false

install:
  - composer install --prefer-dist --verbose

script:
  - ./vendor/bin/phpcs ./
      --standard=ruleset.xml
      --ignore="data/*,vendor/*,core/js/*,core/css/*"
      --colors
      --extensions=php,js,css