language: php 

php:
  - 5.6

install:
  - composer install --prefer-dist --verbose

script:
  - ./vendor/bin/phpcs ./
      --standard=ruleset.xml
      --exclude="$CS_EXCLUDE"
      --ignore="vendor/*"
      --colors
      --extensions=php
